name: memorization_app
description: An app supporting memorization.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.1.0
  csv_repository:
    path: packages/csv_repository
  decks_repository:
    path: packages/decks_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hive_flutter: ^1.1.0
  settings_repository:
    path: packages/settings_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  mockingjay: ^0.3.0

flutter:
  uses-material-design: true
