name: memorization_app
description: A Flutter project supporting memorization.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  csv: ^5.0.1
  csv_repository:
    path: packages/csv_repository
  decks_repository:
    path: packages/decks_repository
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  settings_repository:
    path: packages/settings_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  mocktail: ^0.3.0
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true
