name: decks_repository
description: A repository which manages decks domain, uses Hive database.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  equatable: ^2.0.5
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
